project:
  type: website

website:
  title: "Workshop: Interactive Data Analysis with Shiny"
  reader-mode: true
  google-analytics: "G-BVZNWTMFX1"
  twitter-card: true
  site-url: https://bookdown.org/paul/shiny-workshop/
  repo-url: https://github.com/paulcbauer/shiny-workshop
  repo-actions: [edit, issue]
  sidebar:
    title: "Interactive Data Analysis with Shiny"
    style: "floating"
    search: true
    collapse-level: 2
    collapse-section: 2
    contents:
      - section: "1 The workshop"
        contents:
          - 01-workshop.qmd
      - section: "2 Introduction"
        contents:
          - 02-introduction.qmd
      - section: "3 User interface (UI)"
        contents:
          - 03-user-interface.qmd
      - section: "4 Server and reactive programming"
        contents:
          - 04-server-reactive-programming.qmd
      - section: "5 Visualizing data in Shiny"
        contents:
          - 05-visualization.qmd
      - section: "6 Embedding maps in Shiny"
        contents:
          - 06-mapping.qmd
      - section: "7 Theming"
        contents:
          - 07-theming.qmd
      - section: "8 A few closing notes on deployment"
        contents:
          - 08-deployment.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    toc-depth: 3
editor: 
  mode: source
execute:
  cache: true
  warning: false
bibliography: [references.bib, packages.bib]
tbl-cap-location: top
fig-cap-location: top