project:
  type: website

website:
  title: "Workshop: Interactive Data Analysis with Shiny"
  reader-mode: true
  google-analytics: "G-BVZNWTMFX1"
  twitter-card: true
  site-url: https://bookdown.org/paul/shiny-workshop/
  repo-url: https://github.com/paulcbauer/shiny-workshop
  issue-url: https://github.com/paulcbauer/shiny-workshop/issues
  repo-actions: [edit, issue]
  sidebar:
    title: "Interactive Data Analysis with Shiny"
    style: "floating"
    search: true
    collapse-level: 1
    collapse-section: 1
    contents:
      - section: "1 The workshop"
        contents:
          - 01-workshop.qmd
      - section: "2 Introduction: why Shiny?"
        contents:
          - 02-introduction.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    toc-depth: 3
editor: 
  mode: source
execute:
  cache: true
  warning: false
bibliography: [references.bib, packages.bib]
tbl-cap-location: top
fig-cap-location: top