name: quarto-deploy

on: 
  push:
    branches:
      - main
      - shiny_workshop_2024
  pull_request:
    branches:
      - main

jobs:
  quarto-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        run: |
          quarto --version
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions